# Generated by Django 4.1 on 2024-04-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_service", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="duration",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="course_service.module",
            ),
        ),
    ]
