# Generated by Django 4.1 on 2024-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorprofile",
            name="about_me",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="designation",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
